#ifndef SETTING_H
#define SETTING_H

#define DEVICE_NAME "LivingRoomAC"

#define MQTT_TOPIC_GET "get/apartment/livingRoom/ac"
#define MQTT_TOPIC_SET "set/apartment/livingRoom/ac"
#define MQTT_TOPIC_LOCK_GET "get/home/lock"

#define AUTOMATED_STATE_AREA_NAME "Apartment"

#define AUTOMATED_STATE_HEAT_ARMED_POWERON true
#define AUTOMATED_STATE_HEAT_ARMED_MODE DAIKIN_HEAT
#define AUTOMATED_STATE_HEAT_ARMED_TEMP (byte)18
#define AUTOMATED_STATE_HEAT_DISARMED_POWERON true
#define AUTOMATED_STATE_HEAT_DISARMED_MODE DAIKIN_HEAT
#define AUTOMATED_STATE_HEAT_DISARMED_TEMP (byte)22

#define AUTOMATED_STATE_COOL_ARMED_POWERON false
#define AUTOMATED_STATE_COOL_ARMED_MODE DAIKIN_COOL
#define AUTOMATED_STATE_COOL_ARMED_TEMP (byte)00
#define AUTOMATED_STATE_COOL_DISARMED_POWERON false
#define AUTOMATED_STATE_COOL_DISARMED_MODE DAIKIN_COOL
#define AUTOMATED_STATE_COOL_DISARMED_TEMP (byte)00

#define POWER_ON_VALUE 700  // Above the value of the photoresistor the AC is ON

#define PIN_POWER_ACTUAL A0 // Photoresistor PIN
#define PIN_IR_SEND D2      // IR LED PIN

#endif // ifndef SETTING_H
